# -*- coding: utf-8 -*-
"""main.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1dCqpP8FTUWY_Rz4nOLc0qnfwWecsI9X0
"""

def analise_numero(numeros):
  if not numeros:
    return 'A lista não contém números'

  maior = max(numeros)
  menor = min(numeros)
  media = sum(numeros)/len(numeros)
  pares = len([num for num in numeros if num %2 ==0])

  return {'média':media,
        'maior número':maior,
        'menor número':menor,
        'quantidade de números pares':pares}
